setx CAHSPER_DB_DATASOURCE_URL "jdbc:mariadb://127.0.0.1/cahsper?useUnicode=true&characterEncoding=utf8mb4"
setx CAHSPER_DB_DATASOURCE_USER "root"
setx CAHSPER_DB_DATASOURCE_PASSWORD "pass"
setx CAHSPER_DB_CONNECTION_TIMEOUT 30000
setx CAHSPER_DB_MAXIMUM_POOLSIZE 6

setx CAHSPER_HTTP_HOST "127.0.0.1"
setx CAHSPER_HTTP_PORT 9001
