version: '3'
services:
  cahsper_mariadb:
    image: yoshinorin/docker-mariadb:10.4.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: cahsper
    volumes:
      - ./data:/var/lib/mysql
    hostname: cahsper-mariadb
    networks:
      - cahsper
    container_name: cahsper-mariadb
    expose:
      - "3306"
    ports:
      - "3306:3306"
    command: ["mysqld", "--character-set-server=utf8mb4"]
    restart: unless-stopped
  cahsper:
    image: yoshinorin/docker-cahsper:master
    environment:
      CAHSPER_DB_DATASOURCE_URL: jdbc:mariadb://cahsper-mariadb:3306/cahsper?useUnicode=true&characterEncoding=utf8mb4
      CAHSPER_DB_USER: root
      CAHSPER_DB_PASSWORD: pass
      CAHSPER_HTTP_BIND_ADDRESS: 0.0.0.0
      CAHSPER_AWS_COGNITO_ISS: https://cognito-idp.{region}.amazonaws.com/{userPoolId}
      CAHSPER_AWS_COGNITO_APP_CLIENT_ID: cognito_application_client_id
      SBT_OPTS: "-Xms512M -Xmx768M -Xss2M"
    volumes:
      - ./logs:/usr/opt/cahsper/logs
    hostname: cahsper
    networks:
      - cahsper
    container_name: cahsper
    ports:
      - "9001:9001"
    command: ["sbt", "run"]
    depends_on:
      - cahsper_mariadb
networks:
  cahsper:
