CREATE TABLE comments (
  id INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user VARCHAR(32) NOT NULL,
  comment VARCHAR(255) NOT NULL,
  created_at BIGINT UNSIGNED DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
